### ISSUE TITLE
Is `xtask` compatible with `no_std`/cross-compilation target projects?

### ISSUE THREAD

**Issue by U007D** [matklad/cargo-xtask#24]
I am building a (cross-compiled) RISC-V `no_std` project using `cargo build` on x86_64.  It uses a `.cargo/Config.toml` in the crate root to specify a linker script (`memory.lds`) and to set the compilation target:
```toml
[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
runner = "riscv64-unknown-elf-gdb --command=gdb-runner.gdbs"
rustflags = ["-C", "link-arg=-Tmemory.lds"]
```

When I add `xtask` to this project (converting the project to a workspace), `cargo` attempts to build `xtask` as a RISC-V target.  When I move the above `.cargo/Config.toml` out of the workspace root to the application root, `cargo` "forgets" (appears to ignore `.cargo/Config.toml` not in workspace root) to build my app as a RISC-V application, instead simply building it as a native application for my host CPU.

Is `xtask` compatible with `no_std`/foreign target projects?
