### ISSUE TITLE
Shorter x alias like b for build in cargo

### ISSUE THREAD

**Issue by eugenesvk** [matklad/cargo-xtask#31]
For frequently used commands shorter is better, so `cargo b` is better than `cargo build`

What do you think of recommending adding an extra similar alias of `x`? (`r`/`t` are taken, `e` for execute is nice, but doesn't match the project's name)
```toml
[alias]
xtask = "run --package xtask --"
x     = "run --package xtask --"
```
