### ISSUE TITLE
Example does not use the recommended approach (workspaces)

### ISSUE THREAD

**Issue by epage** [matklad/cargo-xtask#8]
> Usually, but not always, the workspace setup is better. 

Seems like we should use workspaces in the example if its the approach we recommend.

**Comment by steveklabnik** [comment]
I'd be interested in hearing more about what exactly this means; what is "the workspace approach"?

**Comment by matklad** [comment]
@steveklabnik so you can put two different things in `.cargo/config` as an alias:

```toml
[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"
```

```toml
[alias]
xtask = "run --package xtask --"
```

The second one requires that `xtask` is a part of the workspace, the first one works even if it isn't.
